mono2: false
encoder:
  type: BiSeNetV2
  detail_channels: [64, 64, 128]
  semantic_channels: [16, 32, 64, 128]
  semantic_expansion_ratio: 6
  bga_channels: 128
  out_indices: [0, 1, 2, 3, 4]
  init_cfg: null
  align_corners: False

decoder:
  type: FCNHead
  in_channels: 128
  in_index: 0
  channels: 1024
  num_convs: 1
  concat_input: False
  dropout_ratio: 0.1
  num_classes: 19
  norm_cfg:
    type: 'SyncBN'
    requires_grad: True
  align_corners: False
