mono2: false
encoder:
  type: ConvNeXt
  arch: base
  out_indices: [ 0, 1, 2, 3 ]
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  gap_before_final_norm: False
  init_cfg:
    type: Pretrained
    checkpoint: https://download.openmmlab.com/mmclassification/v0/convnext/downstream/convnext-base_3rdparty_32xb128-noema_in1k_20220301-2a0ee547.pth
    prefix: backbone.

decoder:
  type: UPerHead
  in_channels: [ 128, 256, 512, 1024 ]
  in_index: [ 0, 1, 2, 3 ]
  pool_scales: [ 1, 2, 3, 6 ]
  channels: 512
  dropout_ratio: 0.1
  align_corners: False

