mono2: false
encoder:
  type: SwinTransformer
  pretrain_img_size: [192, 640]
  embed_dims: 96
  patch_size: 4
  window_size: 7
  mlp_ratio: 4
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  strides: [4, 2, 2, 2]
  out_indices: [0, 1, 2, 3]
  qkv_bias: True
  patch_norm: True
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.3
  use_abs_pos_embed: False
  act_cfg:
    type: GELU
  norm_cfg:
    type: LN
    requires_grad: True
  init_cfg:
    type: Pretrained
    checkpoint: https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/swin/swin_tiny_patch4_window7_224_20220317-1cdeb081.pth

decoder:
  type: UPerHead
  in_channels: [96, 192, 384, 768]
  in_index: [0, 1, 2, 3]
  pool_scales: [1, 2, 3, 6]
  channels: 512
  dropout_ratio: 0.1
  num_classes: 19
  norm_cfg:
    type: SyncBN
    requires_grad: True
  align_corners: False

# d_out: 512
