mono2: false
encoder:
  type: ResNetV1c
  depth: 50
  pretrained: open-mmlab://resnet50_v1c

  
decoder:
  type: UPerHead
  in_channels: [256, 512, 1024, 2048]
  in_index: [0, 1, 2, 3]
  pool_scales: [1, 2, 3, 6]
  channels: 512
  dropout_ratio: 0.1
  align_corners: False
